version: '3.5'

services:
  artifactory:
    deploy:
      placement:
        constraints:
          - node.hostname == ${PLACEMENT_CONSTRAINTS_NODE_HOSTNAME:-hostname}

volumes:
  data-vol:
    name: ${DATA_VOL_NAME:-artifactory-vol}
